USE [master]
GO

/****** Object:  Database [Employeedb]    Script Date: 02-08-2022 13:51:17 ******/
CREATE DATABASE [Employeedb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Employeedb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Employeedb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Employeedb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Employeedb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Employeedb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Employeedb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Employeedb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Employeedb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Employeedb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Employeedb] SET ARITHABORT OFF 
GO

ALTER DATABASE [Employeedb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Employeedb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Employeedb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Employeedb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Employeedb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Employeedb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Employeedb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Employeedb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Employeedb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Employeedb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Employeedb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Employeedb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Employeedb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Employeedb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Employeedb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Employeedb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Employeedb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Employeedb] SET RECOVERY FULL 
GO

ALTER DATABASE [Employeedb] SET  MULTI_USER 
GO

ALTER DATABASE [Employeedb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Employeedb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Employeedb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Employeedb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Employeedb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Employeedb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Employeedb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Employeedb] SET  READ_WRITE 
GO

